### ISSUE TITLE
How to just hash 1 id

### ISSUE THREAD

**Issue by markthelaw** [speps/go-hashids#15]
Hi I only want to hash 1 value at a time. The built in function seems to only support  an array of int as input.

**Comment by speps** [comment]
You should be able to use the Go inline slice syntax, same as the example in the README :

    h.Encode([]int{45, 434, 1313, 99})

Just put one number in there instead of multiple ones. Works with a variable as well :

    h.Encode([]int{myNumber})

**Comment by markthelaw** [comment]
You are right, it works. Thanks
