### ISSUE TITLE
Uint32 and Uint64 version

### ISSUE THREAD

**Issue by pjebs** [speps/go-hashids#21]
Will there be a UInt32 and UInt64 version for these:

`func (h *HashID) Encode(numbers []int) (string, error)`
`func (h *HashID) EncodeInt64(numbers []int64) (string, error)`

Obviously it may create incompatibilities with eg PHP version of library but for some people that is irrelevant.

**Comment by jkramarz** [comment]
@pjebs, I'm sorry to say that, but it will create *compatibility* with PHP version now ;-0

**Comment by dolmen** [comment]
Note that the current implementation rejects negative integers (I haven't checked if it is a limitation of hashids).

**Comment by jkramarz** [comment]
@dolmen, yes it does - only natural numbers and lists of natural numbers can be encoded by hashid.
The upper limit varies by implementation, but supporting up to max uint64 would be the most compatible solution.

**Comment by speps** [comment]
I'll gladly accept PRs for this by the way. Ideally if there's a reference implementation it would also be nice to have the Go library tested against the JS or PHP library on AppVeyor.

**Comment by jkramarz** [comment]
Actually, there's no reference implementation. Most of the libraries (but not Haskell version, AFAIR) are reimplementation of JS version, but with new bugs added ;-)

**Comment by speps** [comment]
As per http://hashids.org :

> Do not try to encode negative numbers. It won't work. The library currently supports only positive numbers and zero. If you're trying to use numbers as flags for something, simply designate the first N number of digits as internal flags.

So negative numbers won't be supported. For now, I am not planning on uint/uint64 versions but it should be straightforward to add and send a PR.
