### ISSUE TITLE
some bug on bit int

### ISSUE THREAD

**Issue by jorise7** [speps/go-hashids#26]
Hi
I am trying to use hashids on golang and big int , the length of number is 18, length of alphabet is 62. 
Encode and decode is work. 
But decode result is wrong. just like that:
243253735426375465
decode result is
243253735426375464
or
243253735426375445

**Comment by speps** [comment]
Would mind explaining your solution given that you closed the issue? It might help someone else or maybe the documentation should be clearer.

**Comment by jorise7** [comment]
sorry, I am checked and found that is not a problem of hashids, but precision loss on  json conversion. (   json string to map[string]interface{}  )
