### ISSUE TITLE
hashing uuids? 

### ISSUE THREAD

**Issue by matthewmueller** [speps/go-hashids#27]
I saw that hashid intentionally doesn't support encoding strings because it's not secure, but I was wondering about hashing uuids as a way to shorten them (not for security). is that possible with this library? thanks!

**Comment by speps** [comment]
I don't really get what you want, UUIDs are already numbers, totalling 128 bits IIRC, but in text form. So you might as well encode this into a hashid :)

**Comment by matthewmueller** [comment]
Hey, thanks for your response! 

What I was looking to do was take my database ID (a UUID) and make a short code for it using hash id.

IIRC, I realized that hashids != short ids, meaning that if i turn a UUID from base64 to base10 and then pass it into the hashid function, it'll still be a huge hash haha.
