### ISSUE TITLE
min length

### ISSUE THREAD

**Issue by fiftysoft** [speps/go-hashids#37]
what is min length can i use to have unique ids ?

**Comment by speps** [comment]
You can't use that library to generate a unique ID. You might prefer https://github.com/rs/xid for this use case.

hashids are for encoding a number/numbers into a user facing string (e.g a URL).

**Comment by fiftysoft** [comment]
hi @speps 

yes i know , i already have unique integer id using this id i generate hashed string .

my q is what is min length ?

**Comment by speps** [comment]
That's how long you want the resulting string to be. It will use more anyway if needed to encore more numbers or bigger numbers. You can leave at the default value and you should be okay.
