### ISSUE TITLE
Not compatible with JS/PHP version

### ISSUE THREAD

**Issue by mvrhov** [speps/go-hashids#45]
If you use the Salt like "\xcb\x91\x96\xd0\xa7\x36\x91\x5b\xbf\xd4" the output of both the JS and PHP version is the same (haven't tested other libraries) but the output of his library is completely different

**Comment by speps** [comment]
Will look into it, thanks for the report.

**Comment by mvrhov** [comment]
The problem is probably that both the alphabet and the salt get converted into the runes. Instead they should be treated as a opaque set of bytes. Or maybe the signature of the function should be to accept []byte but this would be a BC break. I have no idea on how the js version treats the mentioned "strings" but the PHP one treats both of them as single byte characters

**Comment by speps** [comment]
I had a look, it's doing that because you're using latin1 encoding when Go expects strings to be UTF8.
Using code from https://stackoverflow.com/questions/13510458/golang-convert-iso8859-1-to-utf8 I am now getting the same values in both JS and Go.

Go version:
```golang
package main

import "fmt"
import "github.com/speps/go-hashids"

func toUtf8(iso8859_1_buf []byte) string {
	buf := make([]rune, len(iso8859_1_buf))
	for i, b := range iso8859_1_buf {
		buf[i] = rune(b)
	}
	return string(buf)
}

func main() {
	hd := hashids.NewData()
	hd.Alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
	hd.Salt = toUtf8([]byte("\xcb\x91\x96\xd0\xa7\x36\x91\x5b\xbf\xd4"))
	hd.MinLength = 8
	h, _ := hashids.NewWithData(hd)
	e, _ := h.Encode([]int{1, 2, 3})
	fmt.Println(e)
	d, _ := h.DecodeWithError(e)
	fmt.Println(d)
}
```

JS version: https://codepen.io/anon/pen/Lrpyqv

**Comment by mvrhov** [comment]
According to official golang [blog](https://blog.golang.org/strings),

> It's important to state right up front that a string holds arbitrary bytes. It is not required to hold Unicode text, UTF-8 text, or any other predefined format. As far as the content of a string is concerned, it is exactly equivalent to a slice of bytes. 

So I'd still say that the package assumption of string being a valid utf-8 string is wrong as it converts everything into the runes which are unicode and also 32bit on top.

**Comment by mvrhov** [comment]
I've searched around a bit and both php and python versions got requests to support unicode alphabets as they both treat the string as opaque set ob bytes and they both declined, the postgresql implementation also works with "bytes"

**Comment by speps** [comment]
But the JS version uses String.charCodeAt so it supports Unicode technically.

I'm not sure what you're expecting of me here, go-hashids does give you the same values if you give it a UTF8 string so you can go on with your project. I'll probably update the documentation to explain the quirk but that's it.

**Comment by mvrhov** [comment]
What I'm afraid of is that this will somewhat bite somebody.
If you think this is the correct behavior, then there is Valid function inside utf8 package.. 
Maybe on creation both the salt and alphabet could be checked and then the library should panic if either of them is not valid utf8

**Comment by speps** [comment]
I agree it can be confusing hence why I'll update the documentation but I don't think I'll make a validity check. If you're using this library you should understand what it's doing. Every language has their own quirks and this is one of them.
