### ISSUE TITLE
Please add a release tag (for better compatibility with go dep)

### ISSUE THREAD

**Issue by efixler** [speps/go-hashids#48]
go-hashids has one release tag, 1.0.0

There are a few changes to master -- most notably the prototype change to NewWithData() from issue #29 -- that postdate the 1.0.0 tag.

When I added go dep vendoring to a project that depends on hashids, it pulled the 1.0.0 release instead of the latest master, this breaking my build.

This was an easy fix via a dep override, but it'd be nice to have the current master version tagged, since that's probably what most people are using anyway, and it'll save a few minutes of vendoring hassle.

**Comment by speps** [comment]
Just did v2.0.0.

**Comment by efixler** [comment]
Thank you! And thanks for the quick action!
