### ISSUE TITLE
Please support big int

### ISSUE THREAD

**Issue by Pengfei00** [speps/go-hashids#50]
thx

**Comment by oyoy8629** [comment]
uint64 please

**Comment by dolmen** [comment]
HashIDs support only arrays of int64. That's how they are designed. And cross-language compatibility of HashIDs is a major feature.

But you can still encode big int or `uint64` as an array of `int64` on top of this library.

**Comment by msztolcman** [comment]
Hello,
I've added support for BigInt on my own, however @dolmen's comment about cross-lang compatibility stops me from PR here. If anyone is interested, then my solutions is on https://github.com/msztolcman/go-hashids - comments are welcome, I'm not fluent in GoLang :) Maybe it's not best implementation and bad vars naming in few places, but I will fix this later. 

Most important part for me was to have allowed "translation" from UUID to hashid. It works well in PHP, and Go version also was required.
