### ISSUE TITLE
Create v2.0.1, a valid go module version

### ISSUE THREAD

**Issue by dolmen** [speps/go-hashids#57]
Tag v2.0.0 exists, but it is not valid to make a clean Go module version: [v2.0.0 is listed as "incompatible"](https://pkg.go.dev/github.com/speps/go-hashids?tab=versions).

Here is the process to create a v2.0.1 that would fix the problem:
1. Fix the module `go.mod` to add a `/v2` suffix
2. Tag v2.0.1

```
sed -i '' '1s!.*!module github.com/speps/go-hashids/v2!' go.mod
git add go.mod
git commit -m "Fix go module to add /v2 suffix #57"
git tag v2.0.1
git push origin v2.0.1
```

**Comment by speps** [comment]
Thanks for the instructions Olivier, would you want rights on this repo to maintain it a little bit? There isn't much to do usually but I don't have a Go setup anymore to actually do this kind of thing easily.

**Comment by dolmen** [comment]
OK for being maintainer.

**Comment by mfridman** [comment]
+1 for this. Tripped me up a bit seeing v2 but not being able to fetch it. Happy to help as well if needed.

```
go get: module github.com/speps/go-hashids@upgrade found (v2.0.0+incompatible), but does not contain package github.com/speps/go-hashids/v2
```

**Comment by Velocity-** [comment]
Pinging @speps - might be a good idea to give rights to @dolmen so that this repo keeps pace, even if a little. It's the linked one from the hashids website so it's good for the ecosystem.

**Comment by speps** [comment]
I did send an invite to get @dolmen as a collaborator but he hasn't accepted it yet.

**Comment by mfridman** [comment]
@speps I'd be happy to pitch in and help maintain the repo if needed, I do quite a bit of Go development nowadays and have an environment readily available.

Otherwise, I hope @dolmen accepts given they contributed to this repo in the past :)

**Comment by speps** [comment]
As the contributors page shows, @dolmen sent 6 PRs before and is the second main contributor hence why I didn't mind giving full access. I will gladly accept a PR from you of course, no need to have full access :)

**Comment by mfridman** [comment]
Of course, totally understand.

I've created a PR #58. Once its merged we'll need a `v2.0.1` tag. I have a few dependencies on this project so will verify its working as expected as a consumer of this package with the latest changes.

**Comment by speps** [comment]
Thanks @mfridman, it's now merged and a new v2.0.1 tag was made.

**Comment by mfridman** [comment]
Can confirm its working as expected and I'm seeing the correct module version in my go.mod files

```diff
- github.com/speps/go-hashids v2.0.0+incompatible
+ github.com/speps/go-hashids/v2 v2.0.1
```

**Comment by dolmen** [comment]
@speps Could you resend the invitation, please?

I'm using this module in production, and I have some short terms plan to improve the implementation for speed.

**Comment by mfridman** [comment]
@dolmen likewise we use this in production across a few projects. So if you need an extra set of eyes on a PR and/or benchmarking help would be happy to assist, feel free to ping me.

**Comment by dolmen** [comment]
@speps Could you resend the invitation, please?

**Comment by speps** [comment]
Sent
